name: discord-bot-env-v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - python-dotenv
  - flask
  - nb_conda
  - jupyter_contrib_nbextensions
  - ipywidgets
  - pip:
      - discord.py==2.3.1

post-build:
  - jupyter contrib nbextension install --user
  - jupyter nbextension enable --py widgetsnbextension --sys-prefix
